In [2]:
import numpy as np
a = np.array([0.05,0.07,0.06,0.05,0.07,0.10,0.08,0.07,0.06,0.08,0.10,0.09,0.05,0.07,0.09,0.10])
a = a.reshape(4,4)
print(a)

[[0.05 0.07 0.06 0.05]
 [0.07 0.1  0.08 0.07]
 [0.06 0.08 0.1  0.09]
 [0.05 0.07 0.09 0.1 ]]


In [3]:
b = np.linalg.cholesky(a)
print(b)

[[ 2.23606798e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.13049517e-01  4.47213595e-02  0.00000000e+00  0.00000000e+00]
 [ 2.68328157e-01 -8.94427191e-02  1.41421356e-01  0.00000000e+00]
 [ 2.23606798e-01 -3.25111854e-16  2.12132034e-01  7.07106781e-02]]
