In [88]:
import numpy as np

该函数获得T矩阵中最大的非对角元

In [89]:
def getmaxindex(T):
    uper_triangle = np.triu(T, k=1)
    max_index = np.unravel_index(np.argmax(np.abs(uper_triangle)), uper_triangle.shape)
    return max_index

QR算法，设置停止条件为10的-4次方，每次迭代使用3次givens旋转进行QR分解，每5轮迭代输出一次T矩阵

In [90]:
T = np.array([[1.0,-1.0,0.0,0.0],[-1.0,2.0,-1.0,0.0],
              [0.0,-1.0,3.0,-1.0],[0.0,0.0,-1.0,4.0]])
k=0
e = 10**-4
while(np.abs(T[0][1])>e):
    k +=1
    Q = np.diag([1.0,1.0,1.0,1.0])
    R = T
    for i in range(3):
        x1 = R[i][i]
        x2 = R[i+1][i]
        c = x1/np.sqrt(x1**2+x2**2)
        s = x2/np.sqrt(x1**2+x2**2)
        G = np.diag([1.0,1.0,1.0,1.0])
        G[i][i] = c
        G[i+1][i+1] = c
        G[i][i+1] = s
        G[i+1][i] = -1 * s
        R = np.dot(G,R)
        Q = np.dot(G,Q)
    T = np.dot(R,Q.T)
    if(k%5 ==0):
        print(k,T)

5 [[ 4.29276628e+00 -7.21313977e-01 -8.18666697e-17 -5.43358514e-16]
 [-7.21313977e-01  3.55611356e+00 -3.34967464e-01  2.34289842e-16]
 [-4.81736808e-17 -3.34967464e-01  1.89640130e+00 -3.99652715e-04]
 [-2.29665523e-16  2.47087812e-17 -3.99652715e-04  2.54718859e-01]]
10 [[ 4.73418406e+00 -1.31448547e-01 -1.93246264e-16 -5.88422845e-16]
 [-1.31448547e-01  3.18812610e+00 -1.85822775e-02 -5.23882601e-17]
 [-4.91447089e-17 -1.85822775e-02  1.82297108e+00 -2.07643132e-08]
 [-2.15069804e-16 -8.42262145e-17 -2.07643133e-08  2.54718760e-01]]
15 [[ 4.74507887e+00 -1.78120256e-02 -2.13428616e-16 -5.83027491e-16]
 [-1.78120256e-02  3.17748431e+00 -1.15075434e-03 -9.57586083e-17]
 [-4.90024094e-17 -1.15075434e-03  1.82271806e+00 -1.10653406e-12]
 [-2.08367533e-16 -9.96575175e-17 -1.10658672e-12  2.54718760e-01]]
20 [[ 4.74527757e+00 -2.39738535e-03 -2.16210952e-16 -5.82057684e-16]
 [-2.39738535e-03  3.17728658e+00 -7.14944440e-05 -1.01528010e-16]
 [-4.90014462e-17 -7.14944440e-05  1.82271708e+0

jacobi算法，设置停止条件为10的-6次方，每次迭代寻找T的最大非对角元，对其位置进行givens旋转使其变为0，每5轮迭代输出T矩阵

In [91]:
T = np.array([[1.0,-1.0,0.0,0.0],[-1.0,2.0,-1.0,0.0],
              [0.0,-1.0,3.0,-1.0],[0.0,0.0,-1.0,4.0]])
k=0
e = 10**-6
p,q = getmaxindex(T)
item = T[p][q]
while(np.abs(item)>e):
    k+=1
    app = T[p][p]
    aqq = T[q][q]
    apq = T[p][q]
    nenta = (aqq-app)/(2*apq)
    if(nenta>=0):
        t = 1/(nenta+np.sqrt(1+nenta**2))
    else:
        t = -1/(-1*nenta+np.sqrt(1+nenta**2))
    c = 1/np.sqrt(1+t**2)
    s = c*t
    G = np.diag([1.0,1.0,1.0,1.0])
    G[p,p] = c
    G[q,q] = c
    G[p,q]=s
    G[q,p] = -s
    T = np.dot(np.dot(G.T,T),G)
    if(k%5 ==0):
        print(k,T)
    p,q = getmaxindex(T)
    item = T[p][q]

5 [[ 3.02671876e-01  1.98877843e-01  2.83269704e-17  3.90083050e-01]
 [ 1.98877843e-01  3.15387625e+00 -1.13689848e-01  1.15838509e-16]
 [ 6.75012884e-17 -1.13689848e-01  1.84612375e+00  1.98877843e-01]
 [ 3.90083050e-01  2.65066327e-18  1.98877843e-01  4.69732812e+00]]
10 [[ 2.54777527e-01  8.28956379e-04 -9.51832874e-03 -1.84018719e-03]
 [ 8.28956379e-04  3.17728268e+00 -4.96426137e-06  1.61604514e-18]
 [-9.51832874e-03 -4.96426137e-06  1.82265953e+00  8.17755211e-04]
 [-1.84018719e-03 -1.19810643e-16  8.17755211e-04  4.74528026e+00]]
15 [[ 2.54718760e-01 -2.52080934e-12  3.41591974e-07  1.92963626e-10]
 [-2.52071295e-12  3.17728292e+00 -3.08506021e-22 -3.41591974e-07]
 [ 3.41591974e-07 -2.28100143e-17  1.82271708e+00 -2.52080926e-12]
 [ 1.92963590e-10 -3.41591974e-07 -2.52086171e-12  4.74528124e+00]]


sturm序列和对分法求本征值，其中p函数的计算是手动进行的，然后每次迭代对四个零点分别使用对分法，当区间长度小于e时停止

In [104]:
def p0(x):
    return 1
def p1(x):
    return 1-x
def p2(x):
    return x**2-3*x+1
def p3(x):
    return -x**3+6*(x**2)-9*x+2
def p4(x):
    return x**4-10*x**3+32*x**2-35*x+7
p = np.array([p0,p1,p2,p3,p4])
# 没用上
# d = np.array([1.0,2.0,3.0,4.0])
# b = np.array([-1.0,-1.0,-1.0])
# alpha = 0.0
# beta = 5.0
a = np.array([0.0,0.0,0.0,0.0])
b = np.array([5.0,5.0,5.0,5.0])
e = 10**-6
k=0
while(np.abs(a[0]-b[0])>e):
    k+=1
    c = (a+b)/2
    result = np.zeros((5, 4))
    for i in range(4):
        change = 0
        T = np.zeros((5,))
        for j in range(5):
            if(j==0):
                T[j] = p[j](c[i])
            else:
                T[j] = p[j](c[i])
                if(T[j]==0 or T[j]*T[j-1]<0):
                    change+=1
        if(change > (3-i)):
            b[i] = c[i]
        else:
            a[i] = c[i]
    if(k%5 ==0):
        print(k,c)

    


5 [4.84375 3.28125 1.71875 0.15625]
10 [4.74121094 3.17871094 1.82128906 0.25878906]
15 [4.74533081 3.17733765 1.82266235 0.25466919]
20 [4.74527836 3.17728519 1.82271481 0.25472164]


np库函数，作为标准答案

In [ ]:
import numpy as np

# 定义矩阵T
T = np.array([[1.0, -1.0, 0.0, 0.0],
              [-1.0, 2.0, -1.0, 0.0],
              [0.0, -1.0, 3.0, -1.0],
              [0.0, 0.0, -1.0, 4.0]])

# 求解T的本征矢和本征值
eigenvalues, eigenvectors = np.linalg.eig(T)

print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[0.25471876 1.82271708 3.17728292 4.74528124]
Eigenvectors:
[[ 0.77795055 -0.55327108 -0.29117378 -0.06246513]
 [ 0.57979195  0.45518556  0.6339677   0.23394946]
 [ 0.23394946  0.6339677  -0.45518556 -0.57979195]
 [ 0.06246513  0.29117378 -0.55327108  0.77795055]]
